format = """
[ 󰣇 ](bg:#769ff0 fg:#090c0c)\
[](bg:#a47ee8 fg:#769ff0 )\
$directory\
[](fg:#a47ee8 bg:#c3a8f3)\
$git_branch\
$git_status\
[](fg:#c3a8f3 bg:#f8b499)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#f8b499 bg:#3a3f47)\
$time\
[ ](fg:#3a3f47)\
$character"""

[directory]
style = "fg:#e3e5e5 bg:#a47ee8"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#c3a8f3"
format = '[[ $symbol $branch ](fg:#333333 bg:#c3a8f3)]($style)'

[git_status]
style = "bg:#c3a8f3"
format = '[[($all_status$ahead_behind )](fg:#333333 bg:#c3a8f3)]($style)'

[nodejs]
symbol = ""
style = "bg:#f8b499"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#f8b499)]($style)'

[rust]
symbol = ""
style = "bg:#f8b499"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#f8b499)]($style)'

[golang]
symbol = ""
style = "bg:#f8b499"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#f8b499)]($style)'

[php]
symbol = ""
style = "bg:#f8b499"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#f8b499)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#f8b499"
format = '[[  $time ](fg:#ffffff bg:#3a3f47)]($style)'

# Colorscheme:
# Muted Blue: #769ff0
# Lavendar: #a47ee8
# Peach ACcent: #f8b499
# Dark gray: 3a3f47
# Sponsered by ChatGPT
