cursor #cccccc
cursor_text_color #111111

#: Valid values: block, beam, underline.
cursor_shape block
#: Valid values: block, beam, underline, hollow, unchanged.
cursor_shape_unfocused hollow
#: The thickness of the beam cursor (in pts).
cursor_beam_thickness 1.0
#: The thickness of the underline cursor (in pts).
cursor_underline_thickness 1.5

#: Positive values sets cursor blink interval in seconds ()
#: Negative values sets cursor blink interval to system default
#: Zero disables cursor blink
cursor_blink_interval 0
