detect_urls yes

url_color #0087bd
#: The color and style for highlighting URLs on mouse-over.
url_style double
#: url_style can be one of: none, straight, double, curly, dotted, dashed.

underline_hyperlinks always

copy_on_select no

select_by_word_characters @-./_~?&=%+#
#: Characters considered part of a word when double clicking. In
#: addition to these characters any character that is marked as an
#: alphanumeric character in the Unicode database will be matched.
