window_padding_width 0 0
#: Padding between text and window borders. Syntax is the same as in css
single_window_padding_width -1
#: Negative value uses window_padding_width value
inactive_text_alpha 0.5
#: Fade the text in inactive windows by the specified amount
confirm_os_window_close -1
