################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = eDP-1, 1366x768@60.00Hz, 1920x700, 1.0
monitor = HDMI-A-1, 1920x1200@59.95Hz, 0x0, 1.0
