# general {}

# auth {}

background {
    monitor =
    path = ~/Pictures/Wallpapers/KonkukUni.jpg
    color = rgba(51, 51, 51, 0.7) # Fallback color
    blur_passes = 7
    blur_size = 7
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(51, 51, 51, 0.7) # no fill

    outer_color = rgba(a47ee8ee) rgba(e8a47ecc) 45deg
    check_color=rgba(00ff99dd) rgba(ff6633cc) 120deg
    fail_color=rgba(f53c3cdd) rgba(ff6633cc) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    halign = center
    valign = center
}
